
var game_file_list = [
    //以下为自动修改，请勿修改
    //----auto game_file_list start----
	"libs/modules/egret/egret.js",
	"libs/modules/egret/egret.native.js",
	"libs/modules/game/game.js",
	"libs/modules/game/game.native.js",
	"libs/modules/tween/tween.js",
	"libs/modules/res/res.js",
	"libs/modules/dragonBones/dragonBones.js",
	"libs/modules/socket/socket.js",
	"bin-debug/DivSprite.js",
	"bin-debug/LoadingUI.js",
	"bin-debug/Main.js",
	"bin-debug/SSMovieClip.js",
	"bin-debug/gamelibs/EntryDisplayObjectContainer.js",
	"bin-debug/bugs/CacheAsBitmapEmptyContainer.js",
	"bin-debug/bugs/GraphicsDrawArcOne.js",
	"bin-debug/bugs/GraphicsLineDDD.js",
	"bin-debug/bugs/MaskScaleX.js",
	"bin-debug/bugs/XMLParseError.js",
	"bin-debug/gamelibs/LoadResources.js",
	"bin-debug/gamelibs/ResourceUtils.js",
	"bin-debug/test/base64/Base64FromCrossUrl.js",
	"bin-debug/test/base64/Base64FromDisplayObject.js",
	"bin-debug/test/base64/Base64FromTexture.js",
	"bin-debug/test/base64/Base64SaveFromDisplayObject.js",
	"bin-debug/test/base64/Base64SaveFromTexture.js",
	"bin-debug/test/bitmap/BitmapClickCrossMore.js",
	"bin-debug/test/bitmap/BitmapClickSimpleMore.js",
	"bin-debug/test/bitmap/BitmapClickZoom.js",
	"bin-debug/test/bitmap/BitmapDelay.js",
	"bin-debug/test/bitmap/BitmapFillMode.js",
	"bin-debug/test/bitmap/BitmapNormal.js",
	"bin-debug/test/bitmap/BitmapOffsetAnchor.js",
	"bin-debug/test/bitmap/BitmapOffsetAnchorRun.js",
	"bin-debug/test/bitmap/BitmapParams.js",
	"bin-debug/test/bitmap/BitmapRepeat.js",
	"bin-debug/test/bitmap/BitmapRepeatScale.js",
	"bin-debug/test/bitmap/BitmapScale9Btnbg.js",
	"bin-debug/test/bitmap/BitmapScale9FromCreate.js",
	"bin-debug/test/bitmap/BitmapScale9FromRes.js",
	"bin-debug/test/bitmap/BitmapScale9Logo.js",
	"bin-debug/test/bitmap/BitmapScale9Size.js",
	"bin-debug/test/bitmap/BitmapScale9Zoom.js",
	"bin-debug/test/bitmap/BitmapScale9ZoomSize.js",
	"bin-debug/test/bitmap/BitmapScaleX.js",
	"bin-debug/test/bitmap/BitmapSize.js",
	"bin-debug/test/bitmap/BitmapZoom.js",
	"bin-debug/test/bitmaptext/BitmapTextNormal.js",
	"bin-debug/test/bitmaptext/BitmapTextNumberAdd.js",
	"bin-debug/test/bitmaptext/BitmapTextRESNormal.js",
	"bin-debug/test/bitmaptext/BitmapTextWidth.js",
	"bin-debug/test/blendMode/BlendModeErase.js",
	"bin-debug/test/cacheAsbitmap/CacheAsBitmapDelayLoaded.js",
	"bin-debug/test/cacheAsbitmap/CacheAsBitmapEmptyBitmap.js",
	"bin-debug/test/cacheAsbitmap/CacheAsBitmapParentSizeZero.js",
	"bin-debug/test/cacheAsbitmap/CacheAsBitmapTwice.js",
	"bin-debug/test/container/ContainerAddRemoved.js",
	"bin-debug/test/container/ContainerChildRemove.js",
	"bin-debug/test/db/DBBaozha.js",
	"bin-debug/test/db/DBBigFla.js",
	"bin-debug/test/db/DBEffects.js",
	"bin-debug/test/db/DBGirlRun.js",
	"bin-debug/test/db/DBHero.js",
	"bin-debug/test/db/DBNormal.js",
	"bin-debug/test/db/DBRole.js",
	"bin-debug/test/displayObject/DisplayObjectContentBounds.js",
	"bin-debug/test/displayObject/DisplayObjectGetBounds.js",
	"bin-debug/test/displayObject/DisplayObjectSkewValue.js",
	"bin-debug/test/empty/EmptyHelloWorld.js",
	"bin-debug/test/event/EventAddedAndRemoved.js",
	"bin-debug/test/event/EventBoyAndGirl.js",
	"bin-debug/test/event/EventStageADDAndREMOVE.js",
	"bin-debug/test/event/EventStageRESIZE.js",
	"bin-debug/test/event/EventTouchCapture.js",
	"bin-debug/test/filters/FiltersBlur.js",
	"bin-debug/test/filters/FiltersColor.js",
	"bin-debug/test/filters/FiltersGlow.js",
	"bin-debug/test/filters/FiltersShadow.js",
	"bin-debug/test/function/FunctionDefaultValue.js",
	"bin-debug/test/function/FunctionRegExp1.js",
	"bin-debug/test/function/FunctionSuper.js",
	"bin-debug/test/function/FunctionTransmit.js",
	"bin-debug/test/graphics/GraphicsAllUse.js",
	"bin-debug/test/graphics/GraphicsArcCircleDiff.js",
	"bin-debug/test/graphics/GraphicsArcCircleRun.js",
	"bin-debug/test/graphics/GraphicsCurveTo.js",
	"bin-debug/test/graphics/GraphicsDrawArc.js",
	"bin-debug/test/graphics/GraphicsDrawArcFill.js",
	"bin-debug/test/graphics/GraphicsDrawArcLine.js",
	"bin-debug/test/graphics/GraphicsDrawArcRun.js",
	"bin-debug/test/graphics/GraphicsDrawCurve.js",
	"bin-debug/test/graphics/GraphicsDrawEllipse.js",
	"bin-debug/test/graphics/GraphicsDrawLine.js",
	"bin-debug/test/graphics/GraphicsDrawLineClick.js",
	"bin-debug/test/graphics/GraphicsDrawRectMore.js",
	"bin-debug/test/graphics/GraphicsDrawRectTwice.js",
	"bin-debug/test/graphics/GraphicsDrawRoundRect.js",
	"bin-debug/test/graphics/GraphicsGradientFill.js",
	"bin-debug/test/graphics/GraphicsGuaguale.js",
	"bin-debug/test/graphics/GraphicsGuagualeWithRenderTexture.js",
	"bin-debug/test/graphics/GraphicsLineStyle.js",
	"bin-debug/test/graphics/GraphicsLineTest.js",
	"bin-debug/test/graphics/GraphicsLinesDiff.js",
	"bin-debug/test/graphics/GraphicsSomeCircles.js",
	"bin-debug/test/graphics/GraphicsWithoutEndFill.js",
	"bin-debug/test/loader/LoaderBinFile.js",
	"bin-debug/test/loader/LoaderBitmap.js",
	"bin-debug/test/loader/LoaderGetData.js",
	"bin-debug/test/loader/LoaderHttpReqeustGet.js",
	"bin-debug/test/loader/LoaderHttpReqeustPost.js",
	"bin-debug/test/loader/LoaderPostData.js",
	"bin-debug/test/loader/LoaderSound.js",
	"bin-debug/test/loader/LoaderText.js",
	"bin-debug/test/loader/LoaderTextTwice.js",
	"bin-debug/test/mask/MaskArcCircleRun.js",
	"bin-debug/test/mask/MaskCircleGraphics.js",
	"bin-debug/test/mask/MaskDiffMaskAndScroll.js",
	"bin-debug/test/mask/MaskDisplayObject.js",
	"bin-debug/test/mask/MaskMaskGraphics.js",
	"bin-debug/test/mask/MaskMaskRect.js",
	"bin-debug/test/mask/MaskMaskRectChanges.js",
	"bin-debug/test/mask/MaskProgressCircle.js",
	"bin-debug/test/mask/MaskScrollRect.js",
	"bin-debug/test/mask/MaskWithRotation.js",
	"bin-debug/test/mask/MaskWithShapeMove.js",
	"bin-debug/test/movieclip/MovieClipClickCrossMore.js",
	"bin-debug/test/movieclip/MovieClipClickSimpleMore.js",
	"bin-debug/test/movieclip/MovieClipDaSheng.js",
	"bin-debug/test/movieclip/MovieClipEvents.js",
	"bin-debug/test/movieclip/MovieClipHorse.js",
	"bin-debug/test/movieclip/MovieClipNormal.js",
	"bin-debug/test/movieclip/MovieClipNumRun.js",
	"bin-debug/test/movieclip/MovieClipResAnimation.js",
	"bin-debug/test/orientation/OrientationNormal.js",
	"bin-debug/test/other/OtherWinTest.js",
	"bin-debug/test/pixel/PixelMovieClip.js",
	"bin-debug/test/renderTexture/RenderTextureBgTween.js",
	"bin-debug/test/renderTexture/RenderTextureBitmapWithScale.js",
	"bin-debug/test/renderTexture/RenderTextureCircle.js",
	"bin-debug/test/renderTexture/RenderTextureCopyGrids.js",
	"bin-debug/test/renderTexture/RenderTextureDrawTwo.js",
	"bin-debug/test/renderTexture/RenderTextureLess257.js",
	"bin-debug/test/renderTexture/RenderTextureOutSideChildInScreen.js",
	"bin-debug/test/renderTexture/RenderTextureRectSize.js",
	"bin-debug/test/renderTexture/RenderTextureSpriteWithBitmap.js",
	"bin-debug/test/renderTexture/RenderTextureWithTextField.js",
	"bin-debug/test/res/RESAsync.js",
	"bin-debug/test/res/RESBin.js",
	"bin-debug/test/res/RESByUrl.js",
	"bin-debug/test/res/RESDisposeAfterAsync.js",
	"bin-debug/test/res/RESDisposeAfterRenderTexture.js",
	"bin-debug/test/res/RESDisposeAfterUrl.js",
	"bin-debug/test/res/RESDisposeGroupAfterSheet.js",
	"bin-debug/test/res/RESDisposeSheetAfterSheet.js",
	"bin-debug/test/res/RESDisposeSubKeyAfterSheet.js",
	"bin-debug/test/res/RESLoadAndDispose.js",
	"bin-debug/test/res/RESLoadTwoAndDisposeFirst.js",
	"bin-debug/test/res/RESLoadTwoConfigs.js",
	"bin-debug/test/res/RESLoaded.js",
	"bin-debug/test/res/RESLoadedTwice.js",
	"bin-debug/test/res/RESRenderTextureDouble.js",
	"bin-debug/test/res/RESSheet.js",
	"bin-debug/test/res/RESSheetAsync.js",
	"bin-debug/test/scaleMode/ScaleModeCenterWithBg.js",
	"bin-debug/test/scaleMode/ScaleModeClickChangeModes.js",
	"bin-debug/test/scaleMode/ScaleModeFixedWidthAndPortrait.js",
	"bin-debug/test/scrollview/ScrollViewDouble.js",
	"bin-debug/test/scrollview/ScrollViewList.js",
	"bin-debug/test/scrollview/ScrollViewNormal.js",
	"bin-debug/test/sound/SoundAllTest.js",
	"bin-debug/test/sound/SoundCheckStartTime.js",
	"bin-debug/test/sound/SoundClickLoop.js",
	"bin-debug/test/sound/SoundClickPlay.js",
	"bin-debug/test/sound/SoundClickPlayNumbers.js",
	"bin-debug/test/sound/SoundNormal.js",
	"bin-debug/test/sound/SoundPosition.js",
	"bin-debug/test/sound/SoundTimeout.js",
	"bin-debug/test/sound/SoundVolume.js",
	"bin-debug/test/sound/all/test_sound.js",
	"bin-debug/test/spritesheet/SpriteSheetDiff.js",
	"bin-debug/test/spritesheet/SpriteSheetDiffOffSet.js",
	"bin-debug/test/spritesheet/SpriteSheetNormal.js",
	"bin-debug/test/spritesheet/SpriteSheetRepeat.js",
	"bin-debug/test/spritesheet/SpriteSheetSubKey.js",
	"bin-debug/test/spritesheet/SpriteSheetWithParams.js",
	"bin-debug/test/stage/StageDesign.js",
	"bin-debug/test/stage/StageFrameRate.js",
	"bin-debug/test/stage/StageRegionPolicy.js",
	"bin-debug/test/stage/StageScaleModeAndOrientationMode.js",
	"bin-debug/test/textfield/TextFieldAppendText.js",
	"bin-debug/test/textfield/TextFieldBackground.js",
	"bin-debug/test/textfield/TextFieldFamily.js",
	"bin-debug/test/textfield/TextFieldFlow.js",
	"bin-debug/test/textfield/TextFieldFlowEndWithEmpty.js",
	"bin-debug/test/textfield/TextFieldFlowRun.js",
	"bin-debug/test/textfield/TextFieldHref.js",
	"bin-debug/test/textfield/TextFieldHref2.js",
	"bin-debug/test/textfield/TextFieldInput.js",
	"bin-debug/test/textfield/TextFieldInput2.js",
	"bin-debug/test/textfield/TextFieldInputAndArea.js",
	"bin-debug/test/textfield/TextFieldInputNotClick.js",
	"bin-debug/test/textfield/TextFieldInputRotation.js",
	"bin-debug/test/textfield/TextFieldInputText.js",
	"bin-debug/test/textfield/TextFieldInputTextWithDisplayAsPasswordAndRestrict.js",
	"bin-debug/test/textfield/TextFieldLineSpacing.js",
	"bin-debug/test/textfield/TextFieldMaxChars.js",
	"bin-debug/test/textfield/TextFieldMiniWidth.js",
	"bin-debug/test/textfield/TextFieldNormal.js",
	"bin-debug/test/textfield/TextFieldNormalDelay.js",
	"bin-debug/test/textfield/TextFieldOnFocus.js",
	"bin-debug/test/textfield/TextFieldOnFocusAuto.js",
	"bin-debug/test/textfield/TextFieldRestrict.js",
	"bin-debug/test/textfield/TextFieldShowOneByOne.js",
	"bin-debug/test/textfield/TextFieldStrokeRun.js",
	"bin-debug/test/textfield/TextFieldTextArea.js",
	"bin-debug/test/textfield/TextFieldWrap.js",
	"bin-debug/test/texture/TextureGetPixel32WithDO.js",
	"bin-debug/test/texture/TextureGetPixel32WithImg.js",
	"bin-debug/test/ticker/TickerAddAndRemove.js",
	"bin-debug/test/ticker/TickerLoadingUse.js",
	"bin-debug/test/timer/TimerLoopUse.js",
	"bin-debug/test/timer/TimerStartStop.js",
	"bin-debug/test/touch/TouchBitmap.js",
	"bin-debug/test/touch/TouchContainer.js",
	"bin-debug/test/touch/TouchGraphics.js",
	"bin-debug/test/touch/TouchHideClick.js",
	"bin-debug/test/touch/TouchInputAndButton.js",
	"bin-debug/test/touch/TouchMultiTouches.js",
	"bin-debug/test/touch/TouchReleaseOutSide.js",
	"bin-debug/test/touch/TouchSpriteBitmap.js",
	"bin-debug/test/tween/TweenHasMore.js",
	"bin-debug/test/tween/TweenLoopWithShape.js",
	"bin-debug/test/tween/TweenNormal.js",
	"bin-debug/test/tween/TweenPauseAndPlay.js",
	"bin-debug/test/tween/TweenPausePlayWithWait.js",
	"bin-debug/test/tween/TweenRemoveAll.js",
	"bin-debug/test/tween/TweenRotation.js",
	"bin-debug/test/tween/TweenSingleOp.js",
	"bin-debug/test/tween/TweenTextFieldNumberAdd.js",
	"bin-debug/test/tween/TweenTreeRunRotation.js",
	"bin-debug/test/tween/TweenTweensOp.js",
	"bin-debug/test/tween/TweenTwoTween.js",
	"bin-debug/test/video/VideoInBitmap.js",
	"bin-debug/test/video/VideoNormal.js",
	"bin-debug/test/websocket/WebSocketBinary.js",
	"bin-debug/test/websocket/WebSocketString.js",
	"bin-debug/test/xml/XMLJsonUse.js",
	//----auto game_file_list end----
];

var window = {};

alert = function () {

};

egret_native.setSearchPaths([""]);

egret_native.requireFiles = function () {
    for (var key in game_file_list) {
        var src = game_file_list[key];
        require(src);
    }
};

egret_native.egretInit = function () {
    egret_native.requireFiles();
    egret.TextField.default_fontFamily = "/system/fonts/DroidSansFallback.ttf";
    //egret.dom为空实现
    egret.dom = {};
    egret.dom.drawAsCanvas = function () {
    };
};

egret_native.egretStart = function () {
    var option = {
        //以下为自动修改，请勿修改
        //----auto option start----
		entryClassName: "MaskWithRotation",
		frameRate: 60,
		scaleMode: "showAll",
		contentWidth: 480,
		contentHeight: 800,
		showPaintRect: false,
		showFPS: true,
		fpsStyles: "x:0,y:0,size:18,bgAlpha:0.5",
		showLog: true,
		logFilter: "",
		maxTouches: 99,
		textureScaleFactor: 1
		//----auto option end----
    };

    egret.native.NativePlayer.option = option;
    egret.runEgret();
    egret_native.Label.createLabel(egret.TextField.default_fontFamily, 20, "", 0);
    egret_native.EGTView.preSetOffScreenBufferEnable(true);
};