/**
 * Created by yjtx on 15-6-23.
 */
var TextFieldInput = (function (_super) {
    __extends(TextFieldInput, _super);
    function TextFieldInput() {
        _super.call(this);
    }
    var d = __define,c=TextFieldInput,p=c.prototype;
    p.initRoot = function () {
        var textField = new egret.TextField();
        textField.multiline = false;
        textField.text = "aaa";
        textField.size = 40;
        textField.textColor = 0xff0000;
        textField.type = egret.TextFieldType.INPUT;
        this.addChild(textField);
        textField.x = 10;
        textField.y = 10;
        textField.lineSpacing = 2;
        textField.width = 200;
        textField.height = 40;
        textField.background = true;
        textField.backgroundColor = 0x00ffff;
        textField.border = true;
        textField.borderColor = 0x00ff00;
        var textField = new egret.TextField();
        textField.multiline = false;
        textField.text = "aaa";
        textField.size = 40;
        textField.textColor = 0xff0000;
        textField.type = egret.TextFieldType.INPUT;
        this.addChild(textField);
        textField.x = 220;
        textField.y = 10;
        textField.lineSpacing = 2;
        textField.width = 200;
        textField.height = 30;
        textField.background = true;
        textField.backgroundColor = 0x00ffff;
        textField.border = true;
        textField.borderColor = 0x00ff00;
        var textField = new egret.TextField();
        textField.multiline = false;
        textField.text = "aaa";
        textField.size = 40;
        textField.textColor = 0xff0000;
        textField.type = egret.TextFieldType.INPUT;
        this.addChild(textField);
        textField.x = 10;
        textField.y = 60;
        textField.lineSpacing = 2;
        textField.width = 150;
        textField.height = 200;
        textField.background = true;
        textField.backgroundColor = 0x00ffff;
        textField.border = true;
        textField.borderColor = 0x00ff00;
        textField.textAlign = egret.HorizontalAlign.LEFT;
        var textField = new egret.TextField();
        textField.multiline = false;
        textField.text = "aaa";
        textField.size = 40;
        textField.textColor = 0xff0000;
        textField.type = egret.TextFieldType.INPUT;
        this.addChild(textField);
        textField.x = 170;
        textField.y = 60;
        textField.lineSpacing = 2;
        textField.width = 150;
        textField.height = 200;
        textField.background = true;
        textField.backgroundColor = 0x00ffff;
        textField.border = true;
        textField.borderColor = 0x00ff00;
        textField.textAlign = egret.HorizontalAlign.CENTER;
        var textField = new egret.TextField();
        textField.multiline = false;
        textField.text = "aaa";
        textField.size = 40;
        textField.textColor = 0xff0000;
        textField.type = egret.TextFieldType.INPUT;
        this.addChild(textField);
        textField.x = 330;
        textField.y = 60;
        textField.lineSpacing = 2;
        textField.width = 150;
        textField.height = 200;
        textField.background = true;
        textField.backgroundColor = 0x00ffff;
        textField.border = true;
        textField.borderColor = 0x00ff00;
        textField.textAlign = egret.HorizontalAlign.RIGHT;
        var textField = new egret.TextField();
        textField.multiline = false;
        textField.text = "aaa";
        textField.size = 40;
        textField.textColor = 0xff0000;
        textField.type = egret.TextFieldType.INPUT;
        this.addChild(textField);
        textField.x = 10;
        textField.y = 270;
        textField.lineSpacing = 2;
        textField.width = 150;
        textField.height = 200;
        textField.background = true;
        textField.backgroundColor = 0x00ffff;
        textField.border = true;
        textField.borderColor = 0x00ff00;
        textField.verticalAlign = egret.VerticalAlign.MIDDLE;
        textField.textAlign = egret.HorizontalAlign.LEFT;
        var textField = new egret.TextField();
        textField.multiline = false;
        textField.text = "aaa";
        textField.size = 40;
        textField.textColor = 0xff0000;
        textField.type = egret.TextFieldType.INPUT;
        this.addChild(textField);
        textField.x = 170;
        textField.y = 270;
        textField.lineSpacing = 2;
        textField.width = 150;
        textField.height = 200;
        textField.background = true;
        textField.backgroundColor = 0x00ffff;
        textField.border = true;
        textField.borderColor = 0x00ff00;
        textField.verticalAlign = egret.VerticalAlign.MIDDLE;
        textField.textAlign = egret.HorizontalAlign.CENTER;
        var textField = new egret.TextField();
        textField.multiline = false;
        textField.text = "aaa";
        textField.size = 40;
        textField.textColor = 0xff0000;
        textField.type = egret.TextFieldType.INPUT;
        this.addChild(textField);
        textField.x = 330;
        textField.y = 270;
        textField.lineSpacing = 2;
        textField.width = 150;
        textField.height = 200;
        textField.background = true;
        textField.backgroundColor = 0x00ffff;
        textField.border = true;
        textField.borderColor = 0x00ff00;
        textField.verticalAlign = egret.VerticalAlign.MIDDLE;
        textField.textAlign = egret.HorizontalAlign.RIGHT;
        var textField = new egret.TextField();
        textField.multiline = false;
        textField.text = "aaa";
        textField.size = 40;
        textField.textColor = 0xff0000;
        textField.type = egret.TextFieldType.INPUT;
        this.addChild(textField);
        textField.x = 10;
        textField.y = 480;
        textField.lineSpacing = 2;
        textField.width = 150;
        textField.height = 200;
        textField.background = true;
        textField.backgroundColor = 0x00ffff;
        textField.border = true;
        textField.borderColor = 0x00ff00;
        textField.verticalAlign = egret.VerticalAlign.BOTTOM;
        textField.textAlign = egret.HorizontalAlign.LEFT;
        var textField = new egret.TextField();
        textField.multiline = false;
        textField.text = "aaa";
        textField.size = 40;
        textField.textColor = 0xff0000;
        textField.type = egret.TextFieldType.INPUT;
        this.addChild(textField);
        textField.x = 170;
        textField.y = 480;
        textField.lineSpacing = 2;
        textField.width = 150;
        textField.height = 200;
        textField.background = true;
        textField.backgroundColor = 0x00ffff;
        textField.border = true;
        textField.borderColor = 0x00ff00;
        textField.verticalAlign = egret.VerticalAlign.BOTTOM;
        textField.textAlign = egret.HorizontalAlign.CENTER;
        var textField = new egret.TextField();
        textField.multiline = false;
        textField.text = "aaa";
        textField.size = 40;
        textField.textColor = 0xff0000;
        textField.type = egret.TextFieldType.INPUT;
        this.addChild(textField);
        textField.x = 330;
        textField.y = 480;
        textField.lineSpacing = 2;
        textField.width = 150;
        textField.height = 200;
        textField.background = true;
        textField.backgroundColor = 0x00ffff;
        textField.border = true;
        textField.borderColor = 0x00ff00;
        textField.verticalAlign = egret.VerticalAlign.BOTTOM;
        textField.textAlign = egret.HorizontalAlign.RIGHT;
    };
    return TextFieldInput;
}(EntryDisplayObjectContainer));
egret.registerClass(TextFieldInput,'TextFieldInput');
